services:
  - type: web
    name: kakeibo-backend
    runtime: java
    runtimeVersion: "21"
    buildCommand: "./gradlew clean build -x test"
    startCommand: "java -jar build/libs/kakeibo-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        scope: build
      - key: SPRING_DATASOURCE_USERNAME
        scope: build
      - key: SPRING_DATASOURCE_PASSWORD
        scope: build
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: "validate"
      - key: SERVER_PORT
        value: "8080"
    staticPublishPath: ./build/resources/main/static
    autoDeploy: true
